id: Product

service:
  calls:
  - get: Product
    resp: Product
  - get: Products
    resp: ProductList

definitions:
  ProductList:
    type: array
    items:
      "$ref": Product

properties:
  id:
    "$ref": dataTypes#/definitions/primaryKey
  name:
    type: string
  price:
    type: number
    value: decimal

required:
- name
- price
