id: Cart

service:
  calls:
  - get: Cart
    resp: Cart
  - get: Carts
    resp: CartList

definitions:
  CartList:
    type: array
    items:
      "$ref": Cart

properties:
  id:
    "$ref": dataTypes#/definitions/primaryKey
  items:
    type: array
    items:
      "$ref": Product
      belongsToMany:
        through:
          model: CartItem
          unique: false

required:
- items
